name: fastai_fish
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - aiofiles
  - aiohttp
  - pillow
  - pytorch
  - torchvision
  - cpuonly
  - fastai
  - numpy
  - starlette
  - uvicorn
  - python-multipart